db-configurator:
  enabled: false
  configMapEnvRefs:
  - name: endpoint-db-wm1
  - name: endpoint-db-wm2
  - name: endpoint-db-wm3
    
foo: "bar"
global:
    env: default
    imagePullSecrets:
      - name: default-regcred
        imageRegistry: ccscicd.azurecr.io
      - name: default-regcred
        imageRegistry: ccscicd.azurecr.io

meta:
  from: default
  entry: default
  env: default
  extra: 
    from-1: default-1
    from-2: default-2
