---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ks-repositories
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./platform/repository
  prune: true
  serviceAccountName: flux-reconciler
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: dev
  suspend: true
  dependsOn:
  - name: ks-permissions
    namespace: flux-system