---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ks-permissions
  namespace: default
spec:
  interval: 5m0s
  path: ./platform/permissions
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  dependsOn:
    name: flux-system
    namespace: flux-system