---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ks-vp-dev
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deploy
  prune: true
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
  targetNamespace: flux-system