apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: endpoint-db-attachment
  behavior: create
  envs:
  - endpoint-db-attachment.properties
- name: endpoint-db-cache
  behavior: create
  envs:
  - endpoint-db-cache.properties
- name: app-binaries
  behavior: create
  files:
  - test-file-1.tgz
  - test-file-2.tgz
- name: applications-config
  behavior: create
  files:
  - applications-config.yaml
- name: podinfo-config
  behavior: create
  files:
  - podinfo-values.yaml

