apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- behavior: create
  envs:
  - envs/endpoint-db-attachment.properties
  name: endpoint-db-attachment
- behavior: create
  envs:
  - envs/endpoint-db-cache.properties
  name: endpoint-db-cache
- behavior: create
  files:
  - files/applications-config.yaml
  name: applications-config
- behavior: create
  files:
  - files/podinfo-values.yaml
  name: podinfo-values
- behavior: create
  files:
  - files/test-file-1.tgz
  name: test-file-1
- behavior: create
  files:
  - files/test-file-2.tgz
  name: test-file-2
