apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- release.yaml
- configs/base

namespace: default

configMapGenerator:
- name: config-default
  files:
  - values/values.yaml
  options:
    disableNameSuffixHash: false

configurations:
  - kustomizeconfig.yaml