apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../config-maps/
#- ./../release/

namespace: default

# configMapGenerator:
# - name: vp-config-default
#   files:
#   - values.yaml
#   options:
#     disableNameSuffixHash: true

# patchesStrategicMerge:
# - patch-helmrelease.yaml