apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- release.yaml

namespace: default

configMapGenerator:
- name: config-default
  files:
  - values.yaml
  options:
    disableNameSuffixHash: false

patchesStrategicMerge:
- patch-helmrelease.yaml

configurations:
  - kustomizeconfig.yaml