db-configurator:
  enabled: false
    
foo: "bar"
global:
    env: default
    imagePullSecrets:
      - name: default-regcred
        imageRegistry: ccscicd.azurecr.io
      - name: default-regcred
        imageRegistry: ccscicd.azurecr.io

meta:
  from: default
  entry: default
  env: default
  extra: 
    from: default

