apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../defaults/

namespace: dev

configMapGenerator:
- name: endpoint-db-attachment
  behavior: merge
  envs:
  - endpoint-db-attachment.properties
- name: endpoint-db-cache
  behavior: merge
  envs:
  - endpoint-db-cache.properties
- name: app-binaries
  behavior: replace
  files:
  - test-file-1.tgz
  - test-file-2.tgz
- name: applications-config
  behavior: merge
  files:
  - applications-config.yaml