apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
# - release.yaml
configMapGenerator:
- behavior: create
  envs:
  - envs/api-gateway-policies.properties
  name: api-gateway-policies
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-db-attachment.properties
  name: endpoint-db-attachment
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-db-cache.properties
  name: endpoint-db-cache
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-db-cs.properties
  name: endpoint-db-cs
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-db-drs.properties
  name: endpoint-db-drs
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-db-events.properties
  name: endpoint-db-events
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-db-ewih.properties
  name: endpoint-db-ewih
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-db-questionnaire-read.properties
  name: endpoint-db-questionnaire-read
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-db-questionnaire.properties
  name: endpoint-db-questionnaire
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-db-rcip.properties
  name: endpoint-db-rcip
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-db-wm.properties
  name: endpoint-db-wm
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-ip-ldap.properties
  name: endpoint-ip-ldap
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-is.properties
  name: endpoint-is
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-memcached.properties
  name: endpoint-memcached
  options:
    disableNameSuffixHash: false
- behavior: create
  envs:
  - envs/endpoint-um.properties
  name: endpoint-um
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - files/api-gateway-applications-config.yaml
  name: api-gateway-applications-config
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/api-gateway.yaml
  name: api-gateway
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/db-configurator.yaml
  name: db-configurator
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/db-initializer.yaml
  name: db-initializer
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/ewih-service.yaml
  name: ewih-service
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/globals.yaml
  name: globals
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/integration-server.yaml
  name: integration-server
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/kie-server.yaml
  name: kie-server
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/kie-workbench.yaml
  name: kie-workbench
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/ldap.yaml
  name: ldap
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/memcached.yaml
  name: memcached
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/my-webmethods-server.yaml
  name: my-webmethods-server
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/process-service.yaml
  name: process-service
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/universal-messaging-configurator.yaml
  name: universal-messaging-configurator
  options:
    disableNameSuffixHash: false
- behavior: create
  files:
  - values.yaml=values/universal-messaging.yaml
  name: universal-messaging
  options:
    disableNameSuffixHash: false
